=== swiftbytegbr/jda-boot/src/main/resources/de/swiftbyte/jdaboot/schema/components-v2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://jda-boot.swiftbyte.de/schema/components-v2"
           xmlns="https://jda-boot.swiftbyte.de/schema/components-v2"
           xmlns:c="https://jda-boot.swiftbyte.de/schema/common"
           elementFormDefault="qualified">

    <xs:import namespace="https://jda-boot.swiftbyte.de/schema/common" schemaLocation="common-types.xsd"/>

    <xs:complexType name="defaultVariablesType">
        <xs:sequence>
            <xs:element name="variable" type="c:defaultVarType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="textDisplayType">
        <xs:attribute name="content" type="c:nonEmptyString" use="required"/>
    </xs:complexType>

    <xs:complexType name="separatorType">
        <xs:attribute name="divider" type="xs:string"/>
        <xs:attribute name="spacing" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="thumbnailType">
        <xs:attribute name="url" type="c:nonEmptyString" use="required"/>
        <xs:attribute name="description" type="xs:string"/>
        <xs:attribute name="spoiler" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="fileDisplayType">
        <xs:attribute name="file-name" type="c:nonEmptyString" use="required"/>
        <xs:attribute name="spoiler" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="mediaGalleryItemType">
        <xs:attribute name="url" type="c:nonEmptyString" use="required"/>
        <xs:attribute name="description" type="xs:string"/>
        <xs:attribute name="spoiler" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="mediaGalleryType">
        <xs:sequence>
            <xs:element name="item" type="mediaGalleryItemType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="actionRowType">
        <xs:choice>
            <xs:sequence>
                <xs:element name="button-ref" type="c:refType" maxOccurs="5"/>
            </xs:sequence>
            <xs:element name="string-select-ref" type="c:refType"/>
            <xs:element name="entity-select-ref" type="c:refType"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="sectionContentType">
        <xs:sequence>
            <xs:element name="text-display" type="textDisplayType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="sectionAccessoryType">
        <xs:choice>
            <xs:element name="button-ref" type="c:refType"/>
            <xs:element name="thumbnail" type="thumbnailType"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="sectionType">
        <xs:sequence>
            <xs:element name="content" type="sectionContentType"/>
            <xs:element name="accessory" type="sectionAccessoryType"/>
        </xs:sequence>
        <xs:attribute name="disabled" type="xs:string"/>
    </xs:complexType>

    <xs:group name="containerChildren">
        <xs:choice>
            <xs:element name="text-display" type="textDisplayType"/>
            <xs:element name="separator" type="separatorType"/>
            <xs:element name="file-display" type="fileDisplayType"/>
            <xs:element name="media-gallery" type="mediaGalleryType"/>
            <xs:element name="action-row" type="actionRowType"/>
            <xs:element name="section" type="sectionType"/>
        </xs:choice>
    </xs:group>

    <xs:complexType name="containerType">
        <xs:group ref="containerChildren" maxOccurs="unbounded"/>
        <xs:attribute name="accent-color" type="xs:string"/>
        <xs:attribute name="spoiler" type="xs:string"/>
        <xs:attribute name="disabled" type="xs:string"/>
    </xs:complexType>

    <xs:group name="messageChildren">
        <xs:choice>
            <xs:element name="text-display" type="textDisplayType"/>
            <xs:element name="separator" type="separatorType"/>
            <xs:element name="file-display" type="fileDisplayType"/>
            <xs:element name="media-gallery" type="mediaGalleryType"/>
            <xs:element name="action-row" type="actionRowType"/>
            <xs:element name="container" type="containerType"/>
            <xs:element name="section" type="sectionType"/>
        </xs:choice>
    </xs:group>

    <xs:complexType name="layoutType">
        <xs:sequence>
            <xs:element name="default-variables" type="defaultVariablesType" minOccurs="0"/>
            <xs:group ref="messageChildren" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="c:idType" use="required"/>
    </xs:complexType>

    <xs:element name="components-v2">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="layout" type="layoutType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== swiftbytegbr/jda-boot/src/test/resources/components/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<components-v2 xmlns="https://jda-boot.swiftbyte.de/schema/components-v2"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://jda-boot.swiftbyte.de/schema/components-v2 components-v2.xsd">
    <layout id="test_component_v2">
        <default-variables>
            <variable key="title" value="Test Component V2"/>
            <variable key="test" value="Test Var"/>
        </default-variables>
        <container accent-color="#2ecc71">
            <text-display content="**${title}**"/>
            <section>
                <content>
                    <text-display content="#{command.test.description}"/>
                </content>
                <accessory>
                    <button-ref class="de.swiftbyte.test.TestButton"/>
                </accessory>
            </section>
            <separator spacing="LARGE"/>
            <section>
                <content>
                    <text-display content="This is another section"/>
                </content>
                <accessory>
                    <thumbnail url="${imageUrl}" description="Example Image" spoiler="false"/>
                </accessory>
            </section>
            <separator/>
        </container>
        <separator/>
        <text-display content="This is a top level label"/>
        <container>
            <text-display content="?{app.test}"/>
            <action-row>
                <button-ref id="test_button"/>
                <button-ref id="test_button"/>
            </action-row>
        </container>
        <action-row>
            <entity-select-ref class="de.swiftbyte.test.TestEntitySelectMenu"/>
        </action-row>
        <action-row>
            <string-select-ref class="de.swiftbyte.test.TestStringSelectMenu"/>
        </action-row>
        <media-gallery>
            <item url="https://picsum.photos/200/300"/>
            <item url="https://picsum.photos/200/300"/>
            <item url="https://picsum.photos/200/300"/>
            <item url="https://picsum.photos/200/300"/>
        </media-gallery>
    </layout>
</components-v2>
