=== swiftbytegbr/jda-boot/src/main/resources/de/swiftbyte/jdaboot/schema/modals.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://jda-boot.swiftbyte.de/schema/modals"
           xmlns="https://jda-boot.swiftbyte.de/schema/modals"
           xmlns:c="https://jda-boot.swiftbyte.de/schema/common"
           elementFormDefault="qualified">

    <xs:import namespace="https://jda-boot.swiftbyte.de/schema/common" schemaLocation="common-types.xsd"/>

    <xs:simpleType name="inputStyleType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="SHORT"/>
            <xs:enumeration value="PARAGRAPH"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="stringInputType">
        <xs:attribute name="id" type="c:idType" use="required"/>
        <xs:attribute name="style" type="inputStyleType"/>
        <xs:attribute name="placeholder" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="max-length" type="xs:int"/>
        <xs:attribute name="min-length" type="xs:int"/>
        <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="fileInputType">
        <xs:attribute name="id" type="c:idType" use="required"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="max-values" type="xs:int"/>
        <xs:attribute name="min-values" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="stringSelectOptionType">
        <xs:attribute name="label" type="c:nonEmptyString" use="required"/>
        <xs:attribute name="value" type="c:nonEmptyString" use="required"/>
        <xs:attribute name="description" type="xs:string"/>
        <xs:attribute name="default" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="stringSelectType">
        <xs:sequence>
            <xs:element name="option" type="stringSelectOptionType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="c:idType" use="required"/>
        <xs:attribute name="placeholder" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="max-values" type="xs:int"/>
        <xs:attribute name="min-values" type="xs:int"/>
        <xs:attribute name="disabled" type="xs:boolean"/>
    </xs:complexType>

    <xs:simpleType name="selectTargetType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="USER"/>
            <xs:enumeration value="ROLE"/>
            <xs:enumeration value="CHANNEL"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="entitySelectTargetType">
        <xs:attribute name="type" type="selectTargetType" use="required"/>
    </xs:complexType>

    <xs:complexType name="entitySelectChannelTypeType">
        <xs:attribute name="value" type="c:channelTypeType" use="required"/>
    </xs:complexType>

    <xs:complexType name="entitySelectType">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="target" type="entitySelectTargetType"/>
                <xs:element name="channel-type" type="entitySelectChannelTypeType"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="id" type="c:idType" use="required"/>
        <xs:attribute name="placeholder" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="max-values" type="xs:int"/>
        <xs:attribute name="min-values" type="xs:int"/>
        <xs:attribute name="disabled" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="checkboxType">
        <xs:attribute name="id" type="c:idType" use="required"/>
        <xs:attribute name="default" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="groupOptionType">
        <xs:attribute name="label" type="c:nonEmptyString" use="required"/>
        <xs:attribute name="value" type="c:nonEmptyString" use="required"/>
        <xs:attribute name="description" type="xs:string"/>
        <xs:attribute name="default" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="checkboxGroupType">
        <xs:sequence>
            <xs:element name="option" type="groupOptionType" maxOccurs="10"/>
        </xs:sequence>
        <xs:attribute name="id" type="c:idType" use="required"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="min-values" type="xs:int"/>
        <xs:attribute name="max-values" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="radioGroupType">
        <xs:sequence>
            <xs:element name="option" type="groupOptionType" minOccurs="2" maxOccurs="10"/>
        </xs:sequence>
        <xs:attribute name="id" type="c:idType" use="required"/>
        <xs:attribute name="required" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="labelType">
        <xs:choice>
            <xs:element name="string-input" type="stringInputType"/>
            <xs:element name="file-input" type="fileInputType"/>
            <xs:element name="string-select" type="stringSelectType"/>
            <xs:element name="entity-select" type="entitySelectType"/>
            <xs:element name="checkbox" type="checkboxType"/>
            <xs:element name="checkbox-group" type="checkboxGroupType"/>
            <xs:element name="radio-group" type="radioGroupType"/>
        </xs:choice>
        <xs:attribute name="text" type="c:nonEmptyString" use="required"/>
        <xs:attribute name="description" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="layoutType">
        <xs:sequence>
            <xs:element name="default-variables" type="c:defaultVariablesType" minOccurs="0"/>
            <xs:element name="label" type="labelType" maxOccurs="5"/>
        </xs:sequence>
        <xs:attribute name="id" type="c:idType" use="required"/>
        <xs:attribute name="modal-id" type="c:idType"/>
        <xs:attribute name="modal-class" type="c:nonEmptyString"/>
        <xs:attribute name="title" type="c:nonEmptyString" use="required"/>
    </xs:complexType>

    <xs:element name="modals">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="layout" type="layoutType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== swiftbytegbr/jda-boot/src/test/resources/modals/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<modals xmlns="https://jda-boot.swiftbyte.de/schema/modals"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://jda-boot.swiftbyte.de/schema/modals modals.xsd">
    <layout id="test_modal_layout" modal-class="de.swiftbyte.test.TestModal" title="${title} Modal">
        <default-variables>
            <variable key="title" value="Test XML"/>
        </default-variables>

        <label text="Test">
            <string-input id="test" style="SHORT" placeholder="This is a test modal." required="true"/>
        </label>
        <label text="Test2">
            <string-input id="test2" style="PARAGRAPH" placeholder="This is a test modal 2." min-length="5"
                          max-length="10"/>
        </label>
        <label text="Upload" description="Optional file upload">
            <file-input id="upload" required="false" min-values="0" max-values="1"/>
        </label>
        <label text="Category">
            <string-select id="category" placeholder="Choose a category" min-values="1" max-values="1">
                <option label="Bug" value="bug"/>
                <option label="Feedback" value="feedback" default="true"/>
            </string-select>
        </label>
        <label text="Target User">
            <entity-select id="target_user" placeholder="Select a user" min-values="1" max-values="1" required="true">
                <target type="USER"/>
            </entity-select>
        </label>
    </layout>
</modals>
